# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'biolzma.ui'
#
# Created: Wed Nov  2 17:17:38 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_BioLZMA_Window(object):
    def setupUi(self, BioLZMA_Window):
        BioLZMA_Window.setObjectName(_fromUtf8("BioLZMA_Window"))
        BioLZMA_Window.resize(707, 561)
        BioLZMA_Window.setMinimumSize(QtCore.QSize(707, 125))
        BioLZMA_Window.setMaximumSize(QtCore.QSize(707, 561))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("resources/Knob Shuffle On.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        BioLZMA_Window.setWindowIcon(icon)
        self.pushButton_Start = QtGui.QPushButton(BioLZMA_Window)
        self.pushButton_Start.setEnabled(True)
        self.pushButton_Start.setGeometry(QtCore.QRect(420, 95, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_Start.setFont(font)
        self.pushButton_Start.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Start.setObjectName(_fromUtf8("pushButton_Start"))
        self.lineEdit_Path = QtGui.QLineEdit(BioLZMA_Window)
        self.lineEdit_Path.setGeometry(QtCore.QRect(50, 11, 586, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.lineEdit_Path.setFont(font)
        self.lineEdit_Path.setText(_fromUtf8(""))
        self.lineEdit_Path.setObjectName(_fromUtf8("lineEdit_Path"))
        self.label_13 = QtGui.QLabel(BioLZMA_Window)
        self.label_13.setGeometry(QtCore.QRect(10, 11, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.pushButton_Open = QtGui.QPushButton(BioLZMA_Window)
        self.pushButton_Open.setGeometry(QtCore.QRect(645, 10, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_Open.setFont(font)
        self.pushButton_Open.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Open.setFlat(False)
        self.pushButton_Open.setObjectName(_fromUtf8("pushButton_Open"))
        self.progressBar_Process = QtGui.QProgressBar(BioLZMA_Window)
        self.progressBar_Process.setGeometry(QtCore.QRect(10, 65, 681, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.progressBar_Process.setFont(font)
        self.progressBar_Process.setProperty(_fromUtf8("value"), 0)
        self.progressBar_Process.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_Process.setTextVisible(True)
        self.progressBar_Process.setObjectName(_fromUtf8("progressBar_Process"))
        self.label_10 = QtGui.QLabel(BioLZMA_Window)
        self.label_10.setGeometry(QtCore.QRect(10, 95, 141, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.label_CmpRate = QtGui.QLabel(BioLZMA_Window)
        self.label_CmpRate.setGeometry(QtCore.QRect(160, 95, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_CmpRate.setFont(font)
        self.label_CmpRate.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_CmpRate.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_CmpRate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CmpRate.setObjectName(_fromUtf8("label_CmpRate"))
        self.pushButton_More = QtGui.QPushButton(BioLZMA_Window)
        self.pushButton_More.setEnabled(True)
        self.pushButton_More.setGeometry(QtCore.QRect(560, 95, 131, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_More.setFont(font)
        self.pushButton_More.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_More.setObjectName(_fromUtf8("pushButton_More"))
        self.frame = QtGui.QFrame(BioLZMA_Window)
        self.frame.setGeometry(QtCore.QRect(10, 140, 681, 411))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        self.frame.setFont(font)
        self.frame.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame.setLineWidth(1)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_14 = QtGui.QLabel(self.frame)
        self.label_14.setGeometry(QtCore.QRect(480, 15, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.label_Info_Name = QtGui.QLabel(self.frame)
        self.label_Info_Name.setGeometry(QtCore.QRect(310, 15, 141, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_Info_Name.setFont(font)
        self.label_Info_Name.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_Info_Name.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_Info_Name.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Info_Name.setObjectName(_fromUtf8("label_Info_Name"))
        self.label_Info_ID = QtGui.QLabel(self.frame)
        self.label_Info_ID.setGeometry(QtCore.QRect(510, 15, 141, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_Info_ID.setFont(font)
        self.label_Info_ID.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_Info_ID.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_Info_ID.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Info_ID.setObjectName(_fromUtf8("label_Info_ID"))
        self.label_20 = QtGui.QLabel(self.frame)
        self.label_20.setGeometry(QtCore.QRect(250, 15, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.label_15 = QtGui.QLabel(self.frame)
        self.label_15.setGeometry(QtCore.QRect(20, 15, 51, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.label_Info_Type = QtGui.QLabel(self.frame)
        self.label_Info_Type.setGeometry(QtCore.QRect(80, 15, 141, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_Info_Type.setFont(font)
        self.label_Info_Type.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_Info_Type.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_Info_Type.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Info_Type.setObjectName(_fromUtf8("label_Info_Type"))
        self.line_3 = QtGui.QFrame(self.frame)
        self.line_3.setGeometry(QtCore.QRect(20, 35, 641, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        self.line_3.setFont(font)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_33 = QtGui.QLabel(self.frame)
        self.label_33.setGeometry(QtCore.QRect(365, 200, 296, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.label_OrigSize = QtGui.QLabel(self.frame)
        self.label_OrigSize.setGeometry(QtCore.QRect(555, 65, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_OrigSize.setFont(font)
        self.label_OrigSize.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_OrigSize.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_OrigSize.setAlignment(QtCore.Qt.AlignCenter)
        self.label_OrigSize.setObjectName(_fromUtf8("label_OrigSize"))
        self.label = QtGui.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(365, 65, 161, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.label_4 = QtGui.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(365, 135, 141, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(625, 135, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_CmpSize = QtGui.QLabel(self.frame)
        self.label_CmpSize.setGeometry(QtCore.QRect(555, 135, 71, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_CmpSize.setFont(font)
        self.label_CmpSize.setFrameShape(QtGui.QFrame.WinPanel)
        self.label_CmpSize.setFrameShadow(QtGui.QFrame.Sunken)
        self.label_CmpSize.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CmpSize.setObjectName(_fromUtf8("label_CmpSize"))
        self.plainTextEdit_Msg = QtGui.QPlainTextEdit(self.frame)
        self.plainTextEdit_Msg.setGeometry(QtCore.QRect(368, 225, 296, 136))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(8)
        font.setWeight(50)
        font.setBold(False)
        self.plainTextEdit_Msg.setFont(font)
        self.plainTextEdit_Msg.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.plainTextEdit_Msg.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.plainTextEdit_Msg.setUndoRedoEnabled(False)
        self.plainTextEdit_Msg.setLineWrapMode(QtGui.QPlainTextEdit.NoWrap)
        self.plainTextEdit_Msg.setReadOnly(True)
        self.plainTextEdit_Msg.setPlainText(_fromUtf8(""))
        self.plainTextEdit_Msg.setObjectName(_fromUtf8("plainTextEdit_Msg"))
        self.label_2 = QtGui.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(625, 65, 31, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.progressBar_CmpSize = QtGui.QProgressBar(self.frame)
        self.progressBar_CmpSize.setGeometry(QtCore.QRect(365, 160, 296, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.progressBar_CmpSize.setFont(font)
        self.progressBar_CmpSize.setMaximum(10000)
        self.progressBar_CmpSize.setProperty(_fromUtf8("value"), 0)
        self.progressBar_CmpSize.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_CmpSize.setTextVisible(False)
        self.progressBar_CmpSize.setObjectName(_fromUtf8("progressBar_CmpSize"))
        self.progressBar_OrigSize = QtGui.QProgressBar(self.frame)
        self.progressBar_OrigSize.setGeometry(QtCore.QRect(365, 90, 296, 23))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.progressBar_OrigSize.setFont(font)
        self.progressBar_OrigSize.setMaximum(10000)
        self.progressBar_OrigSize.setProperty(_fromUtf8("value"), 0)
        self.progressBar_OrigSize.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_OrigSize.setTextVisible(False)
        self.progressBar_OrigSize.setObjectName(_fromUtf8("progressBar_OrigSize"))
        self.frame_2 = QtGui.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(20, 60, 331, 341))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtGui.QFrame.WinPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.label_3 = QtGui.QLabel(self.frame_2)
        self.label_3.setGeometry(QtCore.QRect(15, 9, 221, 16))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.line = QtGui.QFrame(self.frame_2)
        self.line.setGeometry(QtCore.QRect(15, 20, 301, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        self.line.setFont(font)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.widget = QtGui.QWidget(self.frame_2)
        self.widget.setGeometry(QtCore.QRect(20, 59, 291, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.widget.setFont(font)
        self.widget.setObjectName(_fromUtf8("widget"))
        self.spinBox_SCLength = QtGui.QSpinBox(self.widget)
        self.spinBox_SCLength.setGeometry(QtCore.QRect(220, 10, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.spinBox_SCLength.setFont(font)
        self.spinBox_SCLength.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_SCLength.setReadOnly(False)
        self.spinBox_SCLength.setMinimum(1)
        self.spinBox_SCLength.setMaximum(12)
        self.spinBox_SCLength.setProperty(_fromUtf8("value"), 3)
        self.spinBox_SCLength.setObjectName(_fromUtf8("spinBox_SCLength"))
        self.label_26 = QtGui.QLabel(self.widget)
        self.label_26.setGeometry(QtCore.QRect(10, 10, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.comboBox_SCType = QtGui.QComboBox(self.widget)
        self.comboBox_SCType.setGeometry(QtCore.QRect(60, 10, 81, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        self.comboBox_SCType.setFont(font)
        self.comboBox_SCType.setObjectName(_fromUtf8("comboBox_SCType"))
        self.comboBox_SCType.addItem(_fromUtf8(""))
        self.comboBox_SCType.addItem(_fromUtf8(""))
        self.comboBox_SCType.addItem(_fromUtf8(""))
        self.label_27 = QtGui.QLabel(self.widget)
        self.label_27.setGeometry(QtCore.QRect(160, 10, 61, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.label_34 = QtGui.QLabel(self.frame_2)
        self.label_34.setGeometry(QtCore.QRect(20, 39, 291, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(True)
        font.setUnderline(False)
        font.setBold(False)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.label_35 = QtGui.QLabel(self.frame_2)
        self.label_35.setGeometry(QtCore.QRect(20, 109, 291, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.widget_2 = QtGui.QWidget(self.frame_2)
        self.widget_2.setGeometry(QtCore.QRect(20, 129, 291, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.widget_2.setFont(font)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.label_24 = QtGui.QLabel(self.widget_2)
        self.label_24.setGeometry(QtCore.QRect(10, 10, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.comboBox_PrecType = QtGui.QComboBox(self.widget_2)
        self.comboBox_PrecType.setGeometry(QtCore.QRect(60, 10, 221, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        self.comboBox_PrecType.setFont(font)
        self.comboBox_PrecType.setObjectName(_fromUtf8("comboBox_PrecType"))
        self.comboBox_PrecType.addItem(_fromUtf8(""))
        self.comboBox_PrecType.addItem(_fromUtf8(""))
        self.widget_3 = QtGui.QWidget(self.frame_2)
        self.widget_3.setGeometry(QtCore.QRect(20, 199, 291, 131))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.widget_3.setFont(font)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.spinBox_DictLev = QtGui.QSpinBox(self.widget_3)
        self.spinBox_DictLev.setGeometry(QtCore.QRect(115, 10, 166, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.spinBox_DictLev.setFont(font)
        self.spinBox_DictLev.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_DictLev.setMinimum(0)
        self.spinBox_DictLev.setMaximum(26)
        self.spinBox_DictLev.setProperty(_fromUtf8("value"), 23)
        self.spinBox_DictLev.setObjectName(_fromUtf8("spinBox_DictLev"))
        self.label_23 = QtGui.QLabel(self.widget_3)
        self.label_23.setGeometry(QtCore.QRect(10, 10, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.label_22 = QtGui.QLabel(self.widget_3)
        self.label_22.setGeometry(QtCore.QRect(10, 40, 81, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.spinBox_FastByte = QtGui.QSpinBox(self.widget_3)
        self.spinBox_FastByte.setGeometry(QtCore.QRect(115, 40, 166, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.spinBox_FastByte.setFont(font)
        self.spinBox_FastByte.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.spinBox_FastByte.setReadOnly(False)
        self.spinBox_FastByte.setMinimum(5)
        self.spinBox_FastByte.setMaximum(256)
        self.spinBox_FastByte.setProperty(_fromUtf8("value"), 128)
        self.spinBox_FastByte.setObjectName(_fromUtf8("spinBox_FastByte"))
        self.label_25 = QtGui.QLabel(self.widget_3)
        self.label_25.setGeometry(QtCore.QRect(10, 70, 91, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.comboBox_LzmaMode = QtGui.QComboBox(self.widget_3)
        self.comboBox_LzmaMode.setGeometry(QtCore.QRect(115, 70, 166, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        self.comboBox_LzmaMode.setFont(font)
        self.comboBox_LzmaMode.setObjectName(_fromUtf8("comboBox_LzmaMode"))
        self.comboBox_LzmaMode.addItem(_fromUtf8(""))
        self.comboBox_LzmaMode.addItem(_fromUtf8(""))
        self.comboBox_LzmaMode.addItem(_fromUtf8(""))
        self.label_7 = QtGui.QLabel(self.widget_3)
        self.label_7.setGeometry(QtCore.QRect(10, 100, 101, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.comboBox_Matchfinder = QtGui.QComboBox(self.widget_3)
        self.comboBox_Matchfinder.setGeometry(QtCore.QRect(115, 100, 166, 22))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        self.comboBox_Matchfinder.setFont(font)
        self.comboBox_Matchfinder.setObjectName(_fromUtf8("comboBox_Matchfinder"))
        self.comboBox_Matchfinder.addItem(_fromUtf8(""))
        self.comboBox_Matchfinder.addItem(_fromUtf8(""))
        self.comboBox_Matchfinder.addItem(_fromUtf8(""))
        self.comboBox_Matchfinder.addItem(_fromUtf8(""))
        self.comboBox_Matchfinder.addItem(_fromUtf8(""))
        self.comboBox_Matchfinder.addItem(_fromUtf8(""))
        self.comboBox_Matchfinder.addItem(_fromUtf8(""))
        self.comboBox_Matchfinder.addItem(_fromUtf8(""))
        self.comboBox_Matchfinder.addItem(_fromUtf8(""))
        self.comboBox_Matchfinder.addItem(_fromUtf8(""))
        self.comboBox_Matchfinder.addItem(_fromUtf8(""))
        self.label_36 = QtGui.QLabel(self.frame_2)
        self.label_36.setGeometry(QtCore.QRect(20, 179, 291, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setItalic(True)
        font.setBold(False)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.pushButton_About = QtGui.QPushButton(self.frame)
        self.pushButton_About.setGeometry(QtCore.QRect(370, 370, 291, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        self.pushButton_About.setFont(font)
        self.pushButton_About.setText(_fromUtf8(""))
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("resources/logo.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_About.setIcon(icon1)
        self.pushButton_About.setIconSize(QtCore.QSize(297, 200))
        self.pushButton_About.setObjectName(_fromUtf8("pushButton_About"))
        self.line_4 = QtGui.QFrame(BioLZMA_Window)
        self.line_4.setGeometry(QtCore.QRect(10, 120, 681, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        self.line_4.setFont(font)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.label_11 = QtGui.QLabel(BioLZMA_Window)
        self.label_11.setGeometry(QtCore.QRect(240, 95, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.label_16 = QtGui.QLabel(BioLZMA_Window)
        self.label_16.setGeometry(QtCore.QRect(10, 36, 41, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.lineEdit_DictPath = QtGui.QLineEdit(BioLZMA_Window)
        self.lineEdit_DictPath.setGeometry(QtCore.QRect(50, 36, 586, 20))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(50)
        font.setBold(False)
        self.lineEdit_DictPath.setFont(font)
        self.lineEdit_DictPath.setText(_fromUtf8(""))
        self.lineEdit_DictPath.setObjectName(_fromUtf8("lineEdit_DictPath"))
        self.pushButton_DictOpen = QtGui.QPushButton(BioLZMA_Window)
        self.pushButton_DictOpen.setGeometry(QtCore.QRect(645, 35, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_DictOpen.setFont(font)
        self.pushButton_DictOpen.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_DictOpen.setFlat(False)
        self.pushButton_DictOpen.setObjectName(_fromUtf8("pushButton_DictOpen"))
        self.pushButton_DictClean = QtGui.QPushButton(BioLZMA_Window)
        self.pushButton_DictClean.setGeometry(QtCore.QRect(670, 35, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_DictClean.setFont(font)
        self.pushButton_DictClean.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_DictClean.setFlat(False)
        self.pushButton_DictClean.setObjectName(_fromUtf8("pushButton_DictClean"))
        self.pushButton_Clean = QtGui.QPushButton(BioLZMA_Window)
        self.pushButton_Clean.setGeometry(QtCore.QRect(670, 10, 21, 21))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("FreeSans"))
        font.setPointSize(12)
        font.setWeight(75)
        font.setBold(True)
        self.pushButton_Clean.setFont(font)
        self.pushButton_Clean.setIconSize(QtCore.QSize(24, 24))
        self.pushButton_Clean.setFlat(False)
        self.pushButton_Clean.setObjectName(_fromUtf8("pushButton_Clean"))

        self.retranslateUi(BioLZMA_Window)
        self.comboBox_SCType.setCurrentIndex(0)
        self.comboBox_PrecType.setCurrentIndex(0)
        self.comboBox_LzmaMode.setCurrentIndex(2)
        self.comboBox_Matchfinder.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(BioLZMA_Window)

    def retranslateUi(self, BioLZMA_Window):
        BioLZMA_Window.setWindowTitle(QtGui.QApplication.translate("BioLZMA_Window", "BioLZMA", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Start.setText(QtGui.QApplication.translate("BioLZMA_Window", "Start", None, QtGui.QApplication.UnicodeUTF8))
        self.label_13.setText(QtGui.QApplication.translate("BioLZMA_Window", "File:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Open.setText(QtGui.QApplication.translate("BioLZMA_Window", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.label_10.setText(QtGui.QApplication.translate("BioLZMA_Window", "Compression Rate:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_CmpRate.setText(QtGui.QApplication.translate("BioLZMA_Window", "100", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_More.setText(QtGui.QApplication.translate("BioLZMA_Window", "More >>", None, QtGui.QApplication.UnicodeUTF8))
        self.label_14.setText(QtGui.QApplication.translate("BioLZMA_Window", "ID:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Info_Name.setText(QtGui.QApplication.translate("BioLZMA_Window", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Info_ID.setText(QtGui.QApplication.translate("BioLZMA_Window", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.label_20.setText(QtGui.QApplication.translate("BioLZMA_Window", "Name:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_15.setText(QtGui.QApplication.translate("BioLZMA_Window", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_Info_Type.setText(QtGui.QApplication.translate("BioLZMA_Window", "--", None, QtGui.QApplication.UnicodeUTF8))
        self.label_33.setText(QtGui.QApplication.translate("BioLZMA_Window", "Messages:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_OrigSize.setText(QtGui.QApplication.translate("BioLZMA_Window", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("BioLZMA_Window", "Original Data Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("BioLZMA_Window", "Compressed Size:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_5.setText(QtGui.QApplication.translate("BioLZMA_Window", "KB", None, QtGui.QApplication.UnicodeUTF8))
        self.label_CmpSize.setText(QtGui.QApplication.translate("BioLZMA_Window", "0.00", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("BioLZMA_Window", "KB", None, QtGui.QApplication.UnicodeUTF8))
        self.progressBar_CmpSize.setFormat(QtGui.QApplication.translate("BioLZMA_Window", "%p%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("BioLZMA_Window", "Compression Settings:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_26.setText(QtGui.QApplication.translate("BioLZMA_Window", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_SCType.setItemText(0, QtGui.QApplication.translate("BioLZMA_Window", "Amino", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_SCType.setItemText(1, QtGui.QApplication.translate("BioLZMA_Window", "DNA", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_SCType.setItemText(2, QtGui.QApplication.translate("BioLZMA_Window", "None", None, QtGui.QApplication.UnicodeUTF8))
        self.label_27.setText(QtGui.QApplication.translate("BioLZMA_Window", "Length:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_34.setText(QtGui.QApplication.translate("BioLZMA_Window", "Symbol Convertion:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_35.setText(QtGui.QApplication.translate("BioLZMA_Window", "Precoding:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_24.setText(QtGui.QApplication.translate("BioLZMA_Window", "Type:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PrecType.setItemText(0, QtGui.QApplication.translate("BioLZMA_Window", "Huffman Coding", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_PrecType.setItemText(1, QtGui.QApplication.translate("BioLZMA_Window", "Binary Coding", None, QtGui.QApplication.UnicodeUTF8))
        self.label_23.setText(QtGui.QApplication.translate("BioLZMA_Window", "Dictionary Lv:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_22.setText(QtGui.QApplication.translate("BioLZMA_Window", "Fast Bytes:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_25.setText(QtGui.QApplication.translate("BioLZMA_Window", "LZMA Mode:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_LzmaMode.setItemText(0, QtGui.QApplication.translate("BioLZMA_Window", "0 (Fast)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_LzmaMode.setItemText(1, QtGui.QApplication.translate("BioLZMA_Window", "1 (Normal)", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_LzmaMode.setItemText(2, QtGui.QApplication.translate("BioLZMA_Window", "2 (Best)", None, QtGui.QApplication.UnicodeUTF8))
        self.label_7.setText(QtGui.QApplication.translate("BioLZMA_Window", "Match Finder:", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Matchfinder.setItemText(0, QtGui.QApplication.translate("BioLZMA_Window", "bt2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Matchfinder.setItemText(1, QtGui.QApplication.translate("BioLZMA_Window", "bt3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Matchfinder.setItemText(2, QtGui.QApplication.translate("BioLZMA_Window", "bt4", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Matchfinder.setItemText(3, QtGui.QApplication.translate("BioLZMA_Window", "bt4b", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Matchfinder.setItemText(4, QtGui.QApplication.translate("BioLZMA_Window", "pat2r", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Matchfinder.setItemText(5, QtGui.QApplication.translate("BioLZMA_Window", "pat2", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Matchfinder.setItemText(6, QtGui.QApplication.translate("BioLZMA_Window", "pat2h", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Matchfinder.setItemText(7, QtGui.QApplication.translate("BioLZMA_Window", "pat3h", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Matchfinder.setItemText(8, QtGui.QApplication.translate("BioLZMA_Window", "pat4h", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Matchfinder.setItemText(9, QtGui.QApplication.translate("BioLZMA_Window", "hc3", None, QtGui.QApplication.UnicodeUTF8))
        self.comboBox_Matchfinder.setItemText(10, QtGui.QApplication.translate("BioLZMA_Window", "hc4", None, QtGui.QApplication.UnicodeUTF8))
        self.label_36.setText(QtGui.QApplication.translate("BioLZMA_Window", "LZMA Compression:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_11.setText(QtGui.QApplication.translate("BioLZMA_Window", "%", None, QtGui.QApplication.UnicodeUTF8))
        self.label_16.setText(QtGui.QApplication.translate("BioLZMA_Window", "Dict:", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DictOpen.setText(QtGui.QApplication.translate("BioLZMA_Window", "+", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_DictClean.setText(QtGui.QApplication.translate("BioLZMA_Window", "c", None, QtGui.QApplication.UnicodeUTF8))
        self.pushButton_Clean.setText(QtGui.QApplication.translate("BioLZMA_Window", "c", None, QtGui.QApplication.UnicodeUTF8))

